=== volks73/virtual-pga/tags/Release-1.0.1/configs/vpga3.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pattern">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="inputs" use="required">
					<xs:complexType>
						<xs:element name="input" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="label" type="xs:string"/>
									<xs:element name="pads">
										<xs:complexType>
											<xs:element name="pad" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" use="required"/>						
							</xs:complexType>
						</xs:element>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== volks73/virtual-pga/tags/Release-1.0.1/configs/Example_Pattern3.xml
<?xml version="1.0" encoding="UTF-8"?>
<pattern xmlns="http://nrl.navy.mil/vpga3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vpga3.xsd">
	<name>Example</name>
	<description>An example pattern.</description>
	<inputs>
		<input id="Y1">
			<label>Low</label>
			<pads>
				<pad>1</pad>
			</pads>
		</input>
		<input id="Y2"> 
			<label>Low Sense</label>
			<pads>
				<pad>2</pad>
			</pads>
		</input>
		<input id="Y3">
			<label>High</label>
			<pads>
				<pad>3</pad>
			</pads>
		</input>
		<input id="Y4">
			<label>High Sense</label>
			<pads>
				<pad>4</pad>
			</pads>
		</input>
	</inputs>
</pattern>
